### ISSUE TITLE
enable students to view grades

### ISSUE THREAD

**Issue by aeSzelag** [aeSzelag/scrumGithubFlow#1]
User Story
As a student, I want to be able to check my grades online so I can keep up with how well I'm going in my classes.

Description
Grades should be able to be posted online with easy access to view.

Task List:
-[] make space on webpage for text
-[] create  responsive table to display grades 
-[] connect to grade database
-[] display only the student's grade who is logged in

Acceptance Criteria
Current grades are visible to the correct student when logged in.

Acceptance Tests
The student is able to view their current semester grades.

**Comment by eyu776** [comment]
> User Story As a student, I want to be able to check my grades online so I can keep up with how well I'm going in my classes.
> 
> Description Grades should be able to be posted online with easy access to view.
> 
> Task List: -[] make space on webpage for text -[] create responsive table to display grades -[] connect to grade database -[] display only the student's grade who is logged in
> 
> Acceptance Criteria Current grades are visible to the correct student when logged in.
> 
> Acceptance Tests The student is able to view their current semester grades.

to create a task list in markdown:

```
- [ ] {task 1}
- [ ] {task 2}
- [ ] {task 3}
```

e.g.
### Task List
- [ ] make space on webpage for text
- [ ] create responsive table to display grades
- [ ] connect to grade database
- [ ] display only the student's grade who is logged in
